# https://travis-ci.org/conda/constructor

language: python
sudo: false

branches:
  only:
    - master
env:
  global:
    - CONSTRUCTOR_CACHE=/tmp/constructor_travis_ci

matrix:
  include:
    # Linux
    - os: linux
      arch: amd64
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.6
    - os: linux
      arch: arm64
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.6
    - os: linux
      arch: amd64
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true
    - os: linux
      arch: arm64
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true
    - os: linux
      arch: amd64
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
    - os: linux
      arch: arm64
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
    # OSX
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.7
  allow_failures:
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true

cache:
  directories:
    - $HOME/condacache/pkgs
    - $HOME/.cache/pip

install:
  - mkdir -p $HOME/condacache/pkgs
  # Install latest miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$TRAVIS_CPU_ARCH" == "arm64" ]]; then
        wget -q "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh;
        chmod +x archiconda.sh;
        bash archiconda.sh -b -p /opt/conda/;
        SUDO="sudo";
        $SUDO rm -rf /usr/bin/lsb_release;
        $SUDO chmod -R 777 /opt/conda/*;
        $SUDO cp -r /opt/conda/bin/* /usr/bin/;
        $SUDO cp -r /opt/conda/lib/libpython* /usr/lib/;
        $SUDO cp /opt/conda/bin/conda conda.exe;
        export PATH=$PATH:/opt/conda/bin;
        $SUDO chmod +x conda.exe; 
        python setup.py install;
      else
        wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe;
        chmod +x conda.exe;
      fi
    else
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe -O conda.exe;
    fi
  - export CONDA_PKGS_DIRS="~/condacache/pkgs"
  - export CONDA_ALWAYS_YES="true"
  - export CONDA_AUTO_UPDATE_CONDA="false"
  - if [ "${CONDA_CANARY}" = "true" ]; then
      $SUDO ./conda.exe create -y -q -p ~/miniconda -c conda-canary conda=4.6 python=$PYTHON_VERSION;
    else
      $SUDO ./conda.exe create -y -q -p ~/miniconda -c conda-canary conda=$CONDA_VERSION python=$PYTHON_VERSION;
    fi
  - $SUDO ./conda.exe install -y -p ~/miniconda pillow>=3.1 ruamel_yaml conda-forge::codecov pytest pytest-cov
  - source "$HOME"/miniconda/bin/activate
  # Install this package
  - $SUDO python setup.py develop
  # this needs
  - $SUDO mkdir $HOME/miniconda/standalone_conda
  - $SUDO cp conda.exe $HOME/miniconda/standalone_conda/conda.exe
  # diagnostics
  - conda info
  - conda init
  - source "$HOME"/miniconda/bin/activate
  - export PATH=$PATH:/opt/conda/bin
  - conda list

script:
  - pytest --cov=constructor constructor
  - $SUDO python scripts/run_examples.py

after_success:
  - codecov
